[connection]
id=OpenAP
uuid=9e8b3934-543c-4985-9474-50c279f08c6c
type=wifi
autoconnect=false
interface-name=wlan0

[wifi]
band=a
mode=ap
ssid=AllezViensOnEstBien

[ipv4]
address1=10.42.0.1/24
method=shared

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
